// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRGrPIFnUs0boDqQBEQ59xuQ89mbYJiP8',
    appId: '1:265370666169:android:cdf1c54463b85b10f58768',
    messagingSenderId: '265370666169',
    projectId: 'pizza-361ab',
    storageBucket: 'pizza-361ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP2IgO6SQs-4EQjn-aw46ydGT8CEyfrmU',
    appId: '1:265370666169:ios:61fac507a91e5e4df58768',
    messagingSenderId: '265370666169',
    projectId: 'pizza-361ab',
    storageBucket: 'pizza-361ab.appspot.com',
    iosBundleId: 'com.example.pizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA_8jeQmZADHxJQ0icuEvxAffiWTz8ogo',
    appId: '1:265370666169:web:91e89193172e30eaf58768',
    messagingSenderId: '265370666169',
    projectId: 'pizza-361ab',
    authDomain: 'pizza-361ab.firebaseapp.com',
    storageBucket: 'pizza-361ab.appspot.com',
  );
}
